name: Build main

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Patch Dionysus
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git submodule update --init --recursive
          ./dionysus jar

      - uses: actions/upload-artifact@v2
        with:
          name: Dionysus-JDK8
          path: dionysus-paperclip.jar
