name: Build PR

on: [pull_request]

jobs:
  build-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get PR info
        run: |
          echo "PR=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')" >> $GITHUB_ENV

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Patch Dionysus
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git submodule update --init --recursive
          ./dionysus jar

      - uses: actions/upload-artifact@v2
        with:
          name: Dionysus-PR${{ env.PR }}-JDK8
          path: dionysus-paperclip.jar
