name: Build PR

on: [pull_request]

jobs:
  build-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get PR info
        run: |
          echo "PR=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')" >> $GITHUB_ENV

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Patch Dionysus
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git submodule update --init --recursive
          ./dionysus patch

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Dionysus
        run: |
          ./dionysus build
          ./scripts/paperclip.sh

      - uses: actions/upload-artifact@v2
        with:
          name: Dionysus-PR${{ env.PR }}-JDK8
          path: dionysus-paperclip.jar
